group_one/urls.py
from django.contrib import admin
from django.urls import path, include
from movieworld import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('movieworld/', include('movieworld.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movieworld/urls.py
from django.urls import path
from movieworld import views

app_name = 'movieworld'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('sign_up/', views.sign_up, name='sign_up'),
    path('login/', views.user_login, name='login'),
    path('login_check',views.login_check, name='login_check'),
    path('logout/', views.user_logout, name='logout'),
    path('search', views.search, name='search'),
    path('search/<query>/page/<page_no>/', views.page, name='page'),
    path('<imdb_id>', views.movieDetails, name='details'),
    path('<imdb_id>/review', views.review, name='reviews'),
    path('reviewed_select/',views.reviewed_select, name='reviewed_select'),
    path('my_reviews/', views.my_reviews, name='my_reviews'),
    path('reviews_all/',views.reviews_all, name='reviews_all'),
    path('movies_select/', views.movies_select, name='movies_select')
]

movieworld/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core import files
import requests
from io import BytesIO
from PIL import Image

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    picture = models.ImageField(upload_to = 'profile_images', blank=True)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        SIZE = 50, 50
        
        if self.picture:
            pic = Image.open(self.picture.path)
            pic.thumbnail(SIZE, Image.LANCZOS)
            pic.save(self.picture.path)

    def __str__(self):
        return self.user.username


class Movie(models.Model):

    movie_id = models.CharField(max_length=20, blank=True)
    title = models.CharField(max_length=200)
    year = models.CharField(max_length=25, blank = True)
    genre = models.CharField(max_length=250, blank=True)
    language = models.CharField(max_length=250, blank=True)
    poster = models.ImageField(upload_to='movies', blank = True)
    poster_url = models.URLField(blank=True)
    totalSeasons = models.CharField(max_length=3, blank=True)
    plot = models.CharField(max_length=900, blank=True)

    class Meta:
        verbose_name_plural = 'Movies'

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if self.poster == '' and self.poster_url !='':
            value = requests.get(self.poster_url)
            pb = BytesIO()
            pb.write(value.content)
            pb.flush()
            file_name = self.poster_url.split("/")[-1]
            self.poster.save(file_name, files.File(pb), save=False)
        return super().save(*args, **kwargs)
        
CHOICES = [
	(1, '1 - Do not Recommend'),
	(2, '2 - Bad'),
	(3, '3 - Reccomendable'),
	(4, '4 - Very Good'),
	(5, '5 - Master Piece'),
]

class Review(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    review = models.TextField(max_length=3000, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    review_number = models.PositiveSmallIntegerField(default=0, choices=CHOICES)

    def __str__(self):
        return self.user.username

movieworld/forms.py
from movieworld.models import UserProfile
from django import forms
from django.contrib.auth.models import User
from movieworld.models import Review, CHOICES

 
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password',)
        

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('picture',)

class RateForm(forms.ModelForm):
	review = forms.CharField(widget=forms.Textarea(attrs={'class': 'materialize-textarea'}), required=False)
	review_number = forms.ChoiceField(choices=CHOICES, widget=forms.Select(), required=True)

	class Meta:
		model = Review
		fields = ('review', 'review_number')

movieworld/views.py
from contextlib import nullcontext
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect,  JsonResponse
from django.urls import reverse
from django.template import loader
from movieworld.models import Movie, Review, UserProfile
import requests
from django.db.models import Avg
from django.utils.text import slugify
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from movieworld.forms import UserForm, UserProfileForm, RateForm
from django.contrib.auth.models import User
from django.views.decorators.csrf import csrf_exempt


def index(request):	

	movies=Movie.objects.all()
	reviews= Review.objects.all().values('movie').annotate(avg=Avg('review_number')).values('movie','avg').order_by('-avg')[:5]

	context_dict={}
	context_dict['movies'] = movies
	context_dict['reviews'] = reviews
	print(context_dict)
	
	response = render(request, 'movieworld/index.html', context=context_dict)
	return response

@login_required   
def search(request):
    
    query = request.GET.get('title')
    if query:
        url = 'http://www.omdbapi.com/?apikey=394a7f6d&s=' + query
        response = requests.get(url)
        movie_data = response.json()
        
        context_dict = {
                'query': query,
                'movie_data': movie_data,
                'page_no': 1,
                }

        template = loader.get_template('movieworld/result.html')
        return HttpResponse(template.render(context_dict, request))

    return render(request, 'movieworld/search.html')


@login_required
def movieDetails(request, imdb_id):
    if Movie.objects.filter(movie_id=imdb_id).exists():
        movie_data = Movie.objects.get(movie_id=imdb_id)
        reviews = Review.objects.filter(movie=movie_data)
        database = True

        context = {
			'movie_data': movie_data,
			'reviews': reviews,
			'database': database,
		}
        
    else:
        url = 'http://www.omdbapi.com/?apikey=394a7f6d&i=' + imdb_id
        response = requests.get(url)
        movie_data = response.json()
        
        if movie_data['Type'] == 'movie':
            m, created = Movie.objects.get_or_create(
                movie_id=movie_data['imdbID'],
                title=movie_data['Title'],
                year=movie_data['Year'],
                genre=movie_data['Genre'],
                language=movie_data['Language'],
                poster_url=movie_data['Poster'],
                plot=movie_data['Plot'],
                )

        else:
             m, created = Movie.objects.get_or_create(
                movie_id=movie_data['imdbID'],
                title=movie_data['Title'],
                year=movie_data['Year'],
                genre=movie_data['Genre'],
                language=movie_data['Language'],
                poster_url=movie_data['Poster'],
                plot=movie_data['Plot'],
                totalSeasons=movie_data['totalSeasons'],
                )

        m.save()
        database = False

        context = {
            'movie_data': movie_data,
            'database': database,
        }

    template = loader.get_template('movieworld/reviews.html')

    return HttpResponse(template.render(context, request))

@login_required
def page(request, query, page_no):
    url = 'http://www.omdbapi.com/?apikey=394a7f6d&s=' + query + '&page=' + str(page_no)
    response = requests.get(url)
    movie_data = response.json()

    page_no = int(page_no)+1

    context_dict = {
            'query': query,
            'movie_data': movie_data,
            'page_no': page_no,
            }

    template = loader.get_template('movieworld/result.html')
    return HttpResponse(template.render(context_dict, request))

@login_required
def review(request, imdb_id):
	movie = Movie.objects.get(movie_id=imdb_id)
	user = request.user

	if request.method == 'POST':
		form = RateForm(request.POST)
		if form.is_valid():
			rate = form.save(commit=False)
			rate.user = user
			rate.movie = movie
			rate.save()
			return HttpResponseRedirect(reverse('movieworld:details', args=[imdb_id]))
	else:
		form = RateForm()

	template = loader.get_template('movieworld/review.html')

	context = {
		'form': form, 
		'movie': movie,
	}

	return HttpResponse(template.render(context, request))


def about(request):
	context_dict = {}
	return render(request, 'movieworld/about.html', context_dict)


def sign_up(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(request.POST)
        profile_form = UserProfileForm(request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture'] 

            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()
    
    return render(request, 'movieworld/sign_up.html', context={'user_form': user_form, 'profile_form': profile_form, 'registered': registered})

def user_login(request):
    return render(request, 'movieworld/login.html')


@csrf_exempt
def login_check(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                 login(request, user)
                 request.session['user']=username
                 return JsonResponse({'res':1})
            else:
                 return JsonResponse({'res':2})
        else:
            return JsonResponse({'res':0})
    else:
        return render(request, 'movieworld/login.html')

 
@login_required
def user_logout(request):
    logout(request)
    return redirect(reverse('movieworld:index'))


@csrf_exempt
def reviewed_select(request):

#get the username from the session
    user=request.session.get('user')
    
    try:
        language=request.POST.get('language')
        sort=request.POST.get('sort')
        genre=request.POST.get('genre')

    except:
        language=None
        sort=None
        genre=None

    try:
        user=User.objects.get(username=user)
        reviews=Review.objects.filter(user=user)

#set a flag to check if get data from review model or movie model
        flag=0

        if(language):
            movies=Movie.objects.filter(language__contains=language)
            flag=1

        if(genre):
            movies=Movie.objects.filter(genre__contains=genre)
            flag=1
        
        if sort=='a_z':
            movies=Movie.objects.order_by('title')
            flag=1
             
        if sort=='z_a' :
            movies=Movie.objects.order_by('-title')
            flag=1

        if sort=='asc':
                reviews=Review.objects.filter(user=user).order_by('date')

        if sort=="desc":
                reviews=Review.objects.filter(user=user).order_by('-date')

# make a list to save the data
        data=[]
        x=0    

#when select data from review model
        if (flag==0):
            for j in reviews:
                data.append([])
                data[x].append(j.movie.title)
                data[x].append(j.movie.year)
                data[x].append(j.movie.genre)
                data[x].append(j.movie.language)
                data[x].append(j.review)
                data[x].append(j.date.strftime('%Y-%m-%d %H:%I:%S'))
                data[x].append(j.review_number)
                x+=1

#when select data from movie model     
        if (flag==1):
            for i in movies: 
                reviews=Review.objects.filter(movie=i,user=user)            
                for j in reviews:
                    data.append([])
                    data[x].append(j.movie.title)
                    data[x].append(j.movie.year)
                    data[x].append(j.movie.genre)
                    data[x].append(j.movie.language)
                    data[x].append(j.review)
                    data[x].append(j.date.strftime('%Y-%m-%d %H:%I:%S'))
                    data[x].append(j.review_number)
                    x+=1
       
    except Movie.DoesNotExist:
        data=None

    return JsonResponse(data, safe=False)

@login_required
def my_reviews(request):

#get username from session
    user=request.session.get('user')
    user=User.objects.get(username=user)

#get all reviews from this user
    reviews = Review.objects.filter(user=user)
    context_dict = {}
    context_dict['reviews'] = reviews

    return render(request, 'movieworld/my_reviews.html', context=context_dict)

@login_required
@csrf_exempt
def movies_select(request):

#clear the session
    request.session['language']=None
    request.session['genre']=None

#get the two variables from dropdown
    try:
        language=request.POST.get('language')
        genre=request.POST.get('genre')

    except:
        language=None
        genre=None

#save the two options into session
    request.session['language']=language
    request.session['genre']=genre
    
    return JsonResponse({'res':1})

@login_required
def reviews_all(request):   

#get the option from session
    try:
        language=request.session.get('language')
        genre=request.session.get('genre')
        print(language)
    except:
        language=None
        genre=None

#get all movies 
    movies = Movie.objects.all()

#filter the movies if the option exists
    if language:
        movies=Movie.objects.filter(language__contains=language)
        request.session['language']=None

    if genre:
        movies=Movie.objects.filter(genre__contains=genre)

templates/movieworld/about.html
<!-- @Author Xinyao -->
{% extends 'movieworld/base.html' %}
{% load staticfiles %}

{% block title_block %}
	About MovieWorld
{% endblock %}

{% block body_block %}

<head>
    <link rel="stylesheet" type="text/css" href="{% static 'polls/about.css'%}">
</head>


		<div class="text">
			<center><h1>About Movie World</h1></center>
			Here is the about page.<br />
			<strong>This website is a movie-rating platform.</strong><br />
		</div>
		<div class="pic">	
			<img src="{% static "img/logo.jpg" %}" alt="Movie World logo" /> 
		</div>
{% endblock %}

templates/movieworld/base.html
<!-- @Author Xinyao -->
<!DOCTYPE html>
{% load staticfiles %}


<html>
    <head>

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta http-equiv = "X-UA-Compatible" content = "ie=edge">
        
        <link rel="stylesheet" href="{% static 'polls/baseStyle.css' %}">

        <link href="{% static '/img/smalllogo.png' %}" rel="icon">
        <title>

            MovieWorld - 
            {% block title_block %}

            {% endblock %}
        </title>
        
        <link rel="stylesheet" href="{% static 'polls/baseStyle.css' %}">
        <link href="{% static 'img/logo4.jpg' %}" rel="icon">
    </head>
    <body>
        <div>
            <ul>
                <li class="logo"><img src="{% static "img/smalllogo2.png" %}" alt="Movie World logo" /> </li>
                <li><a href="{% url 'movieworld:index' %}">Index</a></li>
                {% if user.is_authenticated %}
                <li style="float:right"><a href="{% url 'movieworld:logout' %}">Logout</a></li>
                <li style="float:right"><a href="{% url 'movieworld:my_reviews' %}">My Reviews</a></li>
                <li style="float:left"><a href="{% url 'movieworld:reviews_all' %}">Reviews</a></li>
                <li><a href="{% url 'movieworld:search' %}">Search Your Movie</a ></li>
                {% else %}
                <li style="float:right"><a href="{% url 'movieworld:sign_up' %}">Sign Up</a></li>
                <li style="float:right"><a href="{% url 'movieworld:login' %}">Login</a></li>           
                {% endif %}
                <li style="float:right"><a href="{% url 'movieworld:about' %}">About</a ></li>
            </ul>
        </div>

            {% block body_block %}
            {% endblock %}
        

        <div>
            {% block side_block %}
            {% endblock %}
        </div>

        <hr />
        <footer class="footer-page">
            <b>GROUP ONE ITECH PROJECT</b> 
        </footer>

      <script src='{% static 'js/jquery-3.6.0.js' %}' ></script>
      <script src='{% static 'js/sign_up.js' %}' ></script>
      <script src='{% static 'js/login.js' %}' ></script>
      <script src='{% static 'js/my_reviews.js' %}' ></script>
      <script src='{% static 'js/reviews_all.js' %}' ></script>
    </body>
    
</html>

templates/movieworld/index.html
<!-- @Author Xinyao -->

{% extends 'movieworld/base.html' %}
{% load staticfiles %}

{% block title_block %}
	Index
{% endblock %}

{% block body_block %}
<head>
	<link rel="stylesheet" type="text/css" href="{% static 'polls/index.css' %}">
</head>

<div class="header" style="background-image:url('../static/img/movies.jpg');">
	<h2><strong>Welcome to Movie World!</strong></h2> 
  </div>
  
  <div class="row">
	<div class="column" >
		<center><h2>PICK OF THE WEEK<br></h2>
			Harry Potter and the Philosopher's Stone</center></div>
	<div class="column" >
		<center><h2>TOP 5 FILMS</h2>
		
		{% if movies %}
			<ul class="list">
			{% for review in reviews %}
				{%for movie in movies%}
			
				{% if movie.id == review.movie %}
					<p><b>{{movie.title}}</b></p>
				{% endif %}

				{%endfor%}				

				<br/>
			{% endfor %}
			</ul>
		{% else %}
			<p>There are no movie present.</p>
		{% endif %}</center></div>
  </div>	

{% endblock %}

templates/movieworld/login.html
{% extends 'movieworld/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Login
{% endblock %}

{% block body_block %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'polls/sign_up.css'%}">
</head>

<form class='form' id="login_form" method="post" action="{% url 'movieworld:login' %}">
    <h1 class='title'>Login</h1>
      {% csrf_token %}

    <div class='inputdiv'>
        <input type="text" class='input' name="username" id='username' value="" size="50" placeholder="a" />
        <label class='label'>Username</label>
    </div>

    <div class='inputdiv'>
        <input type="password" class='input' name="password" id='password' value="" size="50" placeholder="a" />
        <label class='label'>Password</label>
    </div>

<div class='msg'> <span id='msg' > {{msg}} </span></div>

    <input type="button" value="submit" id='submit' class='submit' />
</form>

{% endblock %}

templates/movieworld/my_reviews.html
{% extends 'movieworld/base.html' %}
{% load staticfiles %}

{% block title_block %}
	Movies
{% endblock %}

{% block body_block %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/my_reviews.css'%}">
    <div class="header">
	    <h2><strong>Movie World!</strong></h2> 
    </div>

    <div>
    <center><h2>Reviewed Movies</h2>
    {% csrf_token %}

    <div class='drop_div'>
        <div class='dropdown'>
            <select class='selectbtn' id="sort" onchange="sort();">  
                <div class='options'>
	    <option value="">Sorted by</option> 
	    <option value="a_z">Title A-Z</option> 
	    <option value="z_a">Title Z-A</option> 
                    <option value="asc">Earliest</option> 
	    <option value="desc">Latest</option> 
               </div>
          </select> 
        </div>

  <div class='dropdown'>
            <select class='selectbtn' id="genre" onchange="genre();">  
                <div class='options'>
	    <option value="">Genre</option> 
	    <option value="Action">Action</option> 
	    <option value="Thriller">Triller</option> 
                    <option value="Crime">Crime</option> 
                   <option value="Comedy">Comedy</option>
                   <option value="Adventure">Adventure</option> 
                   <option value="Fiction">Fiction</option>
                   <option value="Mystery">Mystery</option>
                   <option value="Mystery">Suspense</option>
               </div>
           </select> 
        </div>

        <div class='dropdown'>
            <select class='selectbtn' id="language" onchange="language();">  
                <div class='options'>
	    <option value="">Language</option> 
	    <option value="English">English</option> 
	    <option value="Hindi">Hindi</option> 
                    <option value="Chinese">Chinese</option> 
                   <option value="Korean">Korean</option>
                   <option value="Japenese">Japenese</option> 
                   <option value="Latin">Latin</option>
                   <option value="French">French</option> 
               </div>
           </select> 
        </div>
     </div>

     <table class='table'  id='table' >
         <tr>
            <td>Title</td>
            <td id='td_year'>Year</td>
            <td>Genre</td>
            <td id='td_lan'>Language</td>
            <td id='td_rating'>Rating</td>
            <td>Review</td>
            <td id='td_time'>Datetime</td>
        </tr>
    </table>

{% endblock %}

templates/movieworld/result.html
{% extends 'movieworld/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Quote
{% endblock %}

{% block body_block %}

<head>
    <link rel="stylesheet" type="text/css" href="{% static 'polls/result.css'%}">
</head>

  <table class="table table-bordered">
        <thead>
            <tr>
                <th>Poster</th>
                <th>ImdbID</th>
                <th>Title</th>
                <th>Year</th>
            </tr>
        </thead>
        <tbody>
            {% for movie in movie_data.Search %}
            <tr>
                <td><img src="{{ movie.Poster }}"></td>
                <td><a href="{% url 'movieworld:details' movie.imdbID %}">{{ movie.imdbID }}</a></td>
                <td>{{ movie.Title }}</td>
                <td>{{ movie.Year }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    </div>
    <div>
        <a href="{% url 'movieworld:page' query page_no %}">Load More</a>
    </div>

{% endblock %}

templates/movieworld/review.html
{% extends 'movieworld/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Review
{% endblock %}

{% block body_block %}

<head>
    <link rel="stylesheet" type="text/css" href="{% static 'polls/review.css'%}">
</head>

    <div class="card">
        <img src="{{ movie.poster.url }}">
        <div class="container">
            <label class='title'>{{ movie.title }}</label>
            <br>
            <i class='plot'>{{ movie.plot }}</i>
            <form method="post" action="" role="form" >
                {% csrf_token %}
            <div class='number'>
                {{ form.review_number }}
            </div>
            <br>
            <div>
                <label for="textarea1">Comment</label><br/>
                {{ form.review }}
            </div>
            <button type="submit" name="action" class='re-btn'>Review</button>
            </form>
        </div>
    </div>  

{% endblock %}

templates/movieworld/reviews.html
{% extends 'movieworld/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Movies | {{ movie_data.Title }}
{% endblock %}

{% block body_block %}

<head>
    <link rel="stylesheet" type="text/css" href="{% static 'polls/reviews.css'%}">
</head>
    {% if database is True %}
    <div class="card">
        <img src="{{ movie_data.poster.url }}">
        <div class="info">
            <h1> Title: {{ movie_data.title }} </h1>
            <p><b> Year: {{  movie_data.year }} </b></p>
            <p><b> Language: {{ movie_data.language }} </b></p>
            <p><b>Genre:{{ movie_data.genre }}</b></p>
        </div>
        <div>
            <a class='make-btn' href="{% url 'movieworld:reviews' movie_data.movie_id%}">Make your Review</a>
        </div>
    </div>
    {% else %}
    <div class="card">
        <img src="{{ movie_data.Poster }}">
        <div class="info">
            <h1> Title: {{ movie_data.Title }} </h1>
            <p><b> Year: {{  movie_data.Year }} </b></p>
            <p><b> Language: {{ movie_data.Language }} </b></p>
            <p><b>Genre: {{ movie_data.Genre }} </b></p>
        </div>
        <div>
            <a class='make-btn' href="{% url 'movieworld:reviews' movie_data.imdbID%}">Make your Review</a>
        </div>
    </div>
    {% endif %}

    <hr class='hr'>

    <div class="reviews" >
        <h4  class='reviews-header'><b>REVIEWS:</b></h4><br>

        {% for review in reviews %}
         <ul class='ul_white'>
            <li class='li_pic'>
            {% if review.user.profile.picture %}
                <img src="{{ review.user.profile.picture.url }}" alt="">
            {% else %}
                <img src="{% static 'img/avatar2.jpeg' %}" alt="">
            {% endif %}
                </li>
                <li class='li'>@{{ review.user.username }}</li>
                <li class='li'>{{ review.date }}</li>
                <li class='li'>{{ review.review_number }}/5</li>
            </ul>
            <ul class='ul_reviews'><li class='li_reviews'> {{ review.review }}</li> </ul>
            <br/>
        {% endfor %}
    </div>

{% endblock %}

templates/movieworld/reviews_all.html
{% extends 'movieworld/base.html' %}
{% load staticfiles %}

{% block title_block %}
	Movies
{% endblock %}

{% block body_block %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/my_reviews.css'%}">
<link rel="stylesheet" type="text/css" href="{% static 'polls/reviews_all.css'%}">
    <div class="header">
	    <h2><strong>Movie World!</strong></h2> 
    </div>

    <div>
    <center><h2>Reviewed Movies</h2>
    {% csrf_token %}

    <div class='drop_div'>
       <div class='dropdown'>
            <select class='selectbtn' id="select_genre" onchange="select_genre();">  
                <div class='options'>
	    <option value="">Genre</option> 
	    <option value="Action">Action</option> 
	    <option value="Thriller">Triller</option> 
                    <option value="Crime">Crime</option> 
                   <option value="Comedy">Comedy</option>
                   <option value="Adventure">Adventure</option> 
                   <option value="Fiction">Fiction</option>
                   <option value="Mystery">Mystery</option>
                   <option value="Mystery">Suspence</option>  
               </div>
           </select> 
        </div>

        <div class='dropdown'>
            <select class='selectbtn' id="select_lan" onchange="select_lan();">  
                <div class='options'>
	    <option value="">Language</option> 
	    <option value="English">English</option> 
	    <option value="Hindi">Hindi</option> 
                    <option value="Chinese">Chinese</option> 
                    <option value="Korean">Korean</option>
                   <option value="Japenese">Japenese</option> 
                   <option value="Latin">Latin</option>
                   <option value="French">French</option> 
               </div>
           </select> 
        </div>
     </div>

    <div id="tbody">
	{% if reviews %}

		<table>
		{% for review in reviews %}
            {%for movie in movies%}
                {% if review.movie == movie.id %}

                                <ul class='ul'>
                                    <li><a href="{% url 'movieworld:details' movie.movie_id %}">{{ movie.title }}</a></li>
                                    <li class='li'>{{ movie.language }}</li>
                                    <li class='li'>{{ movie.genre }}</li>
                                    <li class='li'>{{ movie.year }}</li> 
                                </ul>

                            {% endif%}
                    {% endfor %}
		{% endfor %}
		</table>

		{% if flag == 0 %}
		<p>There are no movie present.</p>
                                {%  endif %}
	{% endif %}</center></div>
  </div>	

{% endblock %}

templates/movieworld/search.html
{% extends 'movieworld/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Search
{% endblock %}

{% block body_block %}

<head>
    <link rel="stylesheet" type="text/css" href="{% static 'polls/search.css' %}">
</head>

<center><h1 class="m-5"><mark>Search for a Movie</mark></h1></center>
<div class="search bar">
<form>
        {% csrf_token %}
        <input id="textarea1" name="title" value="{{ request.GET.title }}"  placeholder= "Title of Movie" type="text"><br>
    <button class="btn btn-primary" type="submit"></button>
</form>
</div>
{% endblock %}

templates/movieworld/sign_up.html
{% extends 'movieworld/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Sign up
{% endblock %}

{% block body_block %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'polls/sign_up.css'%}">
</head>

{% if registered %}
    <strong>Welcome to Movieworld!</strong>
    
    <a href="{% url 'movieworld:index' %}">Return to the homepage.</a><br />

{% else %}
    <div class='form'>
    <h1 class='title'>Sign up</h1>
    <form id="user_form" method="post" action="{% url 'movieworld:sign_up' %}" enctype="multipart/form-data"  >

    {% csrf_token %}

    <div class='span'><span id="usernameSpan"></span></div>
    <div class='inputdiv'>
        <input type="text" class='input' name="username" id='username' value="" size="50" placeholder="a" />
        <label class='label'>Username</label>
    </div>

    <div class='span'><span id="passwordSpan"></span></div>
    <div class='inputdiv'>
        <input type="password" class='input' name="password" id='password' value="" size="50" placeholder="a" />
        <label class='label'>Password</label>
    </div>

    <div class='span'><span id="confirmSpan"></span></div>
    <div class='inputdiv'>
        <input type="password" class='input' name="confirm" id='confirm' value="" size="50" placeholder="a" />
        <label class='label'>Confirm Password</label>
    </div>

    <div class='pclass'>
        <p>Your password must be: </p>
        <p id='firstline'> 8 characters or more (no spaces) </p>
        <p id='secondline'> 1 lowercase letter </p>
        <p id='thirdline'> 1 uppercase letter </p>
        <p id="fourthline"> 1 number </p>
    </div>
    {% csrf_token %}
    <div class="picturelabel"> {{profile_form.as_p}}</div> 
  
    <input type="submit" name="submit"  id='submit_sign' class='submit' value="Register" />

    </form>
</div>
{% endif %}

{% endblock %}